const canvas=document.getElementById('game');const ctx=canvas.getContext('2d');const scoreEl=document.getElementById('score');const bestEl=document.getElementById('best');const overlay=document.getElementById('overlay');const title=document.getElementById('overlayTitle');const text=document.getElementById('overlayText');const startBtn=document.getElementById('startBtn');
let running=false,last=0,score=0,speed=330,spawnTimer=0,nextSpawn=1.2,obstacles=[],dust=[];let best=Number(localStorage.getItem('jeepRunnerBest')||0);bestEl.textContent=best;
const jeep={x:105,y:0,w:78,h:42,vy:0,grounded:true};const ground=292;
function reset(){score=0;speed=330;spawnTimer=0;nextSpawn=1.15;obstacles=[];dust=[];jeep.y=ground-jeep.h;jeep.vy=0;jeep.grounded=true;scoreEl.textContent='0'}
function start(){reset();running=true;overlay.classList.add('hidden');last=performance.now();requestAnimationFrame(loop)}
function jump(){if(!running){start();return}if(jeep.grounded){jeep.vy=-690;jeep.grounded=false;for(let i=0;i<5;i++)dust.push({x:jeep.x+15,y:ground-5,vx:-70-Math.random()*80,vy:-20-Math.random()*50,a:1})}}
function spawn(){const tall=Math.random()>.72;obstacles.push({x:canvas.width+30,y:ground-(tall?52:34),w:tall?42:48,h:tall?52:34,type:tall?'stump':'rock'});nextSpawn=.9+Math.random()*.85-Math.min(score/4000,.22)}
function collide(a,b){const p=9;return a.x+p<b.x+b.w&&a.x+a.w-p>b.x&&a.y+p<b.y+b.h&&a.y+a.h-p>b.y}
function gameOver(){running=false;const final=Math.floor(score);if(final>best){best=final;localStorage.setItem('jeepRunnerBest',best);bestEl.textContent=best}title.textContent='Trail ended!';text.textContent=`You made it ${final} points. Hit the trail again?`;startBtn.textContent='Run Again';overlay.classList.remove('hidden')}
function update(dt){score+=dt*10;speed=Math.min(620,330+score*.42);scoreEl.textContent=Math.floor(score);jeep.vy+=1800*dt;jeep.y+=jeep.vy*dt;if(jeep.y>=ground-jeep.h){jeep.y=ground-jeep.h;jeep.vy=0;jeep.grounded=true}spawnTimer+=dt;if(spawnTimer>=nextSpawn){spawnTimer=0;spawn()}obstacles.forEach(o=>o.x-=speed*dt);obstacles=obstacles.filter(o=>o.x>-80);dust.forEach(d=>{d.x+=d.vx*dt;d.y+=d.vy*dt;d.a-=dt*1.7});dust=dust.filter(d=>d.a>0);if(obstacles.some(o=>collide(jeep,o)))gameOver()}
function drawBackground(){ctx.fillStyle='#172634';ctx.fillRect(0,0,canvas.width,ground);ctx.fillStyle='#243746';ctx.beginPath();ctx.moveTo(0,220);for(let x=0;x<=canvas.width;x+=120){ctx.lineTo(x,180+Math.sin((x+score*2)/140)*25)}ctx.lineTo(canvas.width,ground);ctx.lineTo(0,ground);ctx.fill();ctx.fillStyle='#654a32';ctx.fillRect(0,ground,canvas.width,canvas.height-ground);ctx.strokeStyle='#8a6748';ctx.lineWidth=3;ctx.setLineDash([18,25]);ctx.beginPath();ctx.moveTo(0,ground+35);ctx.lineTo(canvas.width,ground+35);ctx.stroke();ctx.setLineDash([])}
function drawJeep(){const x=jeep.x,y=jeep.y;ctx.save();ctx.translate(x,y);ctx.fillStyle='#6ea8fe';ctx.fillRect(10,14,61,20);ctx.fillRect(25,3,34,16);ctx.fillStyle='#9dd0ff';ctx.fillRect(29,6,12,10);ctx.fillRect(44,6,11,10);ctx.fillStyle='#dbeafe';ctx.fillRect(69,18,8,7);ctx.fillStyle='#0b0f14';ctx.beginPath();ctx.arc(23,35,10,0,Math.PI*2);ctx.arc(61,35,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#8fa3b8';ctx.beginPath();ctx.arc(23,35,4,0,Math.PI*2);ctx.arc(61,35,4,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#6ea8fe';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(25,4);ctx.lineTo(21,-5);ctx.lineTo(24,-8);ctx.stroke();ctx.restore()}
function drawObstacle(o){ctx.save();if(o.type==='rock'){ctx.fillStyle='#78828d';ctx.beginPath();ctx.moveTo(o.x,o.y+o.h);ctx.lineTo(o.x+7,o.y+10);ctx.lineTo(o.x+24,o.y);ctx.lineTo(o.x+43,o.y+13);ctx.lineTo(o.x+o.w,o.y+o.h);ctx.fill()}else{ctx.fillStyle='#765437';ctx.fillRect(o.x+10,o.y,o.w-20,o.h);ctx.fillRect(o.x,o.y+14,18,10);ctx.fillStyle='#96704b';ctx.fillRect(o.x+15,o.y+5,6,o.h-10)}ctx.restore()}
function draw(){drawBackground();dust.forEach(d=>{ctx.globalAlpha=d.a;ctx.fillStyle='#b9956b';ctx.fillRect(d.x,d.y,5,5);ctx.globalAlpha=1});drawJeep();obstacles.forEach(drawObstacle)}
function loop(now){if(!running)return;const dt=Math.min((now-last)/1000,.032);last=now;update(dt);draw();if(running)requestAnimationFrame(loop)}
startBtn.addEventListener('click',start);window.addEventListener('keydown',e=>{if(['Space','ArrowUp','KeyW'].includes(e.code)){e.preventDefault();jump()}});canvas.addEventListener('pointerdown',e=>{e.preventDefault();jump()});reset();draw();
